// Seed data for the Olleik admin demo. Realistic-ish wholesale food
// inventory + sample customers + sample leads. Loaded on first /admin
// visit; afterwards changes live in localStorage.

import type { AdminState } from "./types";

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

export const SEED_DATA: AdminState = {
  categories: [
    { id: "cat-produce", name: "Produce", description: "Fresh vegetables, fruits, herbs" },
    { id: "cat-dairy", name: "Dairy & Eggs" },
    { id: "cat-meat", name: "Meat & Poultry" },
    { id: "cat-seafood", name: "Seafood" },
    { id: "cat-dry", name: "Dry Goods", description: "Flour, sugar, oils, spices, canned" },
    { id: "cat-beverage", name: "Beverages" },
    { id: "cat-frozen", name: "Frozen" },
    { id: "cat-packaging", name: "Packaging & Disposables" },
  ],
  products: [
    {
      id: "p-tomato-case",
      sku: "PRD-001",
      name: "Vine-Ripe Tomatoes",
      description: "Locally grown, picked at peak ripeness",
      categoryId: "cat-produce",
      unit: "case",
      unitSize: "25 lb",
      listPriceCents: 4800,
      isActive: true,
      createdAt: daysAgo(30),
    },
    {
      id: "p-onion-bag",
      sku: "PRD-002",
      name: "Yellow Onions",
      categoryId: "cat-produce",
      unit: "bag",
      unitSize: "50 lb",
      listPriceCents: 3200,
      isActive: true,
      createdAt: daysAgo(30),
    },
    {
      id: "p-cheddar",
      sku: "DRY-101",
      name: "Aged Cheddar Block",
      categoryId: "cat-dairy",
      unit: "ea",
      unitSize: "5 lb",
      listPriceCents: 2950,
      isActive: true,
      createdAt: daysAgo(25),
    },
    {
      id: "p-mozzarella",
      sku: "DRY-102",
      name: "Whole Milk Mozzarella, Shredded",
      categoryId: "cat-dairy",
      unit: "case",
      unitSize: "6 x 5 lb",
      listPriceCents: 14500,
      isActive: true,
      createdAt: daysAgo(25),
    },
    {
      id: "p-chicken-breast",
      sku: "MEAT-201",
      name: "Boneless Chicken Breast",
      categoryId: "cat-meat",
      unit: "case",
      unitSize: "40 lb",
      listPriceCents: 18900,
      isActive: true,
      createdAt: daysAgo(20),
    },
    {
      id: "p-ground-beef",
      sku: "MEAT-202",
      name: "Ground Beef 80/20",
      categoryId: "cat-meat",
      unit: "case",
      unitSize: "20 x 1 lb",
      listPriceCents: 11200,
      isActive: true,
      createdAt: daysAgo(20),
    },
    {
      id: "p-shrimp",
      sku: "SEA-301",
      name: "Frozen Shrimp 21-25 ct",
      categoryId: "cat-seafood",
      unit: "bag",
      unitSize: "2 lb",
      listPriceCents: 2800,
      isActive: true,
      createdAt: daysAgo(15),
    },
    {
      id: "p-olive-oil",
      sku: "DRY-401",
      name: "Extra Virgin Olive Oil",
      categoryId: "cat-dry",
      unit: "gal",
      unitSize: "1 gal",
      listPriceCents: 4200,
      isActive: true,
      createdAt: daysAgo(60),
    },
    {
      id: "p-ap-flour",
      sku: "DRY-402",
      name: "All-Purpose Flour",
      categoryId: "cat-dry",
      unit: "bag",
      unitSize: "50 lb",
      listPriceCents: 2400,
      isActive: true,
      createdAt: daysAgo(60),
    },
    {
      id: "p-tomato-sauce",
      sku: "DRY-403",
      name: "Crushed San Marzano Tomatoes",
      categoryId: "cat-dry",
      unit: "case",
      unitSize: "6 x #10 can",
      listPriceCents: 5400,
      isActive: true,
      createdAt: daysAgo(40),
    },
    {
      id: "p-coffee",
      sku: "BEV-501",
      name: "Whole Bean Coffee, Medium Roast",
      categoryId: "cat-beverage",
      unit: "bag",
      unitSize: "5 lb",
      listPriceCents: 4800,
      isActive: true,
      createdAt: daysAgo(10),
    },
    {
      id: "p-fries",
      sku: "FRZ-601",
      name: "Shoestring French Fries",
      categoryId: "cat-frozen",
      unit: "case",
      unitSize: "6 x 5 lb",
      listPriceCents: 4200,
      isActive: true,
      createdAt: daysAgo(45),
    },
    {
      id: "p-pizza-box-12",
      sku: "PKG-701",
      name: "Pizza Boxes 12\"",
      categoryId: "cat-packaging",
      unit: "case",
      unitSize: "50 ct",
      listPriceCents: 2100,
      isActive: true,
      createdAt: daysAgo(50),
    },
    {
      id: "p-burger-clamshell",
      sku: "PKG-702",
      name: "Burger Clamshell, Compostable",
      categoryId: "cat-packaging",
      unit: "case",
      unitSize: "500 ct",
      listPriceCents: 8400,
      isActive: true,
      createdAt: daysAgo(50),
    },
  ],
  customers: [
    {
      id: "c-milano",
      businessName: "Milano Pizzeria",
      contactName: "Antonio Russo",
      email: "antonio@milanopizzeria.ca",
      phone: "(613) 555-0142",
      address: "5644 Osgoode Main St, Osgoode, ON",
      status: "active",
      paymentTerms: "net-30",
      notes: "Standing weekly order Tues + Fri. Pizza-only menu.",
      createdAt: daysAgo(180),
    },
    {
      id: "c-als",
      businessName: "Al's Drive-In",
      contactName: "Mohammed Amer",
      email: "amer@alsdrivein.ca",
      phone: "(613) 555-0188",
      address: "1247 Sunset Blvd, Ottawa, ON",
      status: "active",
      paymentTerms: "net-15",
      notes: "Burgers, fries, shakes. High-volume Fri-Sun.",
      createdAt: daysAgo(220),
    },
    {
      id: "c-joeys",
      businessName: "Joey's Cafe",
      contactName: "Joelle Marchand",
      email: "joelle@joeyscafe.ca",
      phone: "(613) 555-0233",
      address: "88 Bank St, Ottawa, ON",
      status: "active",
      paymentTerms: "card-on-file",
      notes: "Independent coffee shop. Specialty roasts, pastries.",
      createdAt: daysAgo(95),
    },
    {
      id: "c-pho-saigon",
      businessName: "Pho Saigon",
      contactName: "Linh Nguyen",
      email: "linh@phosaigon.ca",
      phone: "(613) 555-0301",
      address: "2233 Carling Ave, Ottawa, ON",
      status: "pending",
      paymentTerms: "cod",
      notes: "New account. Awaiting first delivery scheduled Friday.",
      createdAt: daysAgo(7),
    },
  ],
  customerProducts: [
    // Milano: pizza-focused inventory
    { customerId: "c-milano", productId: "p-mozzarella", priceCents: 13800 }, // negotiated
    { customerId: "c-milano", productId: "p-tomato-sauce", priceCents: 5100 },
    { customerId: "c-milano", productId: "p-ap-flour", priceCents: null },
    { customerId: "c-milano", productId: "p-olive-oil", priceCents: 3900 },
    { customerId: "c-milano", productId: "p-pizza-box-12", priceCents: 1950 },
    { customerId: "c-milano", productId: "p-onion-bag", priceCents: null },
    { customerId: "c-milano", productId: "p-tomato-case", priceCents: null },

    // Al's: burger/fries inventory
    { customerId: "c-als", productId: "p-ground-beef", priceCents: 10500 }, // volume discount
    { customerId: "c-als", productId: "p-cheddar", priceCents: null },
    { customerId: "c-als", productId: "p-fries", priceCents: 3950 },
    { customerId: "c-als", productId: "p-onion-bag", priceCents: null },
    { customerId: "c-als", productId: "p-tomato-case", priceCents: null },
    { customerId: "c-als", productId: "p-burger-clamshell", priceCents: 7800 },

    // Joey's: coffee + light food
    { customerId: "c-joeys", productId: "p-coffee", priceCents: 4500 },
    { customerId: "c-joeys", productId: "p-cheddar", priceCents: null },

    // Pho Saigon: new — none assigned yet
  ],
  leads: [
    {
      id: "l-001",
      businessName: "Brewers Lane Tap House",
      contactName: "Sarah O'Donnell",
      email: "sarah@brewerslane.ca",
      phone: "(613) 555-0411",
      message:
        "Looking for a new produce + bun supplier. We do ~80 covers/night, 6 days a week. Currently with Sysco but service has slipped.",
      status: "new",
      submittedAt: daysAgo(1),
    },
    {
      id: "l-002",
      businessName: "Sunrise Bakery",
      contactName: "Hisham Saleh",
      email: "hisham@sunrisebakery.ca",
      phone: "(613) 555-0529",
      message: "Need flour, sugar, butter, and packaging. Daily delivery if possible.",
      status: "contacted",
      submittedAt: daysAgo(3),
    },
    {
      id: "l-003",
      businessName: "Ottawa Catering Co.",
      contactName: "Marie-Claire Dubois",
      email: "mc@ottawacatering.ca",
      phone: "(613) 555-0670",
      status: "approved",
      submittedAt: daysAgo(10),
    },
    {
      id: "l-004",
      businessName: "TacoTaco",
      contactName: "Diego Mendez",
      email: "diego@tacotaco.ca",
      phone: "(613) 555-0788",
      message:
        "Spec request for tortillas (corn + flour), Mexican spices, and produce. Two locations.",
      status: "new",
      submittedAt: daysAgo(0),
    },
  ],
};
